apiVersion: v1
kind: Secret
metadata:
  name: aws-example-facil
  annotations:
    avp.kubernetes.io/path: "testingone" # The name of your AWS Secret
stringData:
  sample-secret: <mysecretvalue>
type: Opaque