kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  namespace: default
  #annotations:
  #  avp.kubernetes.io/path: "kv/data/foo"
stringData:  
  inlineSecret: <path:kv/data/foo#bar>
type: Opaque
