kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  namespace: default
  annotations:
    avp.kubernetes.io/path: "admin/kv/data/foo"
stringData:  
  inlineSecret: <path:admin/kv/data/foo#bar>
type: Opaque
