apiVersion: v1
kind: Secret
metadata:
  name: aws-example-final
stringData:
  passwordx: <path:arn:aws:secretsmanager:us-east-2:088182871277:secret:k8s/preprod/mytestapp1-EIS6k7#password>
type: Opaque
